# Generated by Django 3.0.4 on 2020-03-20 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Item'),
        ),
        migrations.AddField(
            model_name='trade',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Offer'),
        ),
        migrations.AddField(
            model_name='trade',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='account.Account'),
        ),
        migrations.AddField(
            model_name='offer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Item'),
        ),
    ]
